repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [python]

      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        types: [python]

      - id: bandit
        name: bandit
        entry: make bandit
        language: system
        pass_filenames: false
        types: [python]
