name: release

on:
  workflow_run:
    workflows: ["build-test-lint"]
    types: [completed]
    branches: [main]
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    # Run this job if either:
    # 1. The build-test-lint workflow succeeded (for workflow_run events)
    # 2. We're on a v* tag (for push events)
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
