name: release

on:
  workflow_run:
    workflows: ["build-test-lint"]
    types: [completed]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install twine

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Check if tag push
        id: check_tag
        run: |
          git fetch --tags
          if [[ $(git tag --points-at HEAD) ]]; then
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
            echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
          else
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_tag.outputs.IS_TAG == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          tag_name: ${{ steps.check_tag.outputs.TAG_NAME }}
